import org.apache.tools.ant.taskdefs.condition.Os
// import org.jetbrains.dokka.DokkaConfiguration
// import org.jetbrains.dokka.gradle.DokkaTask
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

object Variables {
    // Note: On Linux, if you installed Starsector into ~/something, you have to write /home/<user>/ instead of ~/
    val starsectorDirectory = System.getenv("STARSECTOR_DIRECTORY") ?: "D:/Program Files (x86)/Fractal Softworks/Starsector"


    val modVersion = "1.19.1"
    val jarFileNameBase = "AdvancedGunneryControl-$modVersion"
    val jarFileName = "$jarFileNameBase.jar"
    val sourceJarFileName = "$jarFileNameBase-sources.jar"
    val javadocJarFileName = "$jarFileNameBase-javadoc.jar"

    val modId = "advanced_gunnery_control_dbeaa06e"
    val modName = "AdvancedGunneryControl"
    val author = "DesperatePeter"
    const val description = "A mod that allows fine-tuning of autofire. Press J-key in combat or on the campaign map to access."
    val gameVersion = "0.98a"
    val jarsDir = "jars/agc/AdvancedGunneryControl/$modVersion"
    val jars = arrayOf("$jarsDir/$jarFileName")
    val modPlugin = "com.dp.advancedgunnerycontrol.WeaponControlBasePlugin"
    val isUtilityMod = true
    val masterVersionFile = "https://raw.githubusercontent.com/DesperatePeter/starsector-advanced-weapon-control/master/$modId.version"
    val modThreadId = "21280"

    val modFolderName = modName.replace(" ", "-")

// Scroll down and change the "dependencies" part of mod_info.json, if needed
// LazyLib is needed to use Kotlin, as it provides the Kotlin Runtime
}
//////////////////////
val starsectorCoreDirectory = if(Os.isFamily(Os.FAMILY_WINDOWS)) "${Variables.starsectorDirectory}/starsector-core" else Variables.starsectorDirectory
val starsectorModDirectory = "${Variables.starsectorDirectory}/mods"
val modInModsFolder = File("$starsectorModDirectory/${Variables.modFolderName}")

plugins {
    kotlin("jvm") version "2.1.20"
    java
    // id("org.jetbrains.dokka") version "2.0.0"
}

version = Variables.modVersion

repositories {
    maven(url = uri("$projectDir/libs"))
    jcenter()
}

dependencies {
    // implementation("org.junit.jupiter:junit-jupiter:5.7.0")
    // implementation("junit:junit:4.13.1")
    val kotlinVersionInLazyLib = "2.1.20"

    implementation(fileTree("libs") { include("*.jar") })

    // Get kotlin sdk from LazyLib during runtime, only use it here during compile time
    compileOnly("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersionInLazyLib")

    implementation(
        fileTree(starsectorModDirectory) {
            include(
                "LazyLib*/jars/*.jar",
                "MagicLib*/jars/*.jar",
                "LunaLib*/jars/*.jar",
                "Console Commands*/jars/*.jar",   // with space
            )
        }
    )

    implementation(
        fileTree(starsectorCoreDirectory) {
            include(
                "starfarer.api.jar",
                "starfarer_obf.jar",
                "fs.common_obf.jar",
                "json.jar",
                "xstream-1.4.10.jar",
                "log4j-1.2.9.jar",
                "lwjgl.jar",
                "lwjgl_util.jar"
            )
        }
    )

    compileOnly(
        fileTree("$projectDir/api/src/com/fs/starfarer/api") {
            include("*.java")
        }
    )

}

//java{
//    withSourcesJar()
//    withJavadocJar()
//}

tasks {
    named<Jar>("jar")
    {
        // dependsOn(dokkaJavadoc)
        from(sourceSets.main.get().output)
        destinationDirectory.set(file(Variables.jarsDir))
        archiveFileName.set(Variables.jarFileName)
    }
    named<org.gradle.jvm.tasks.Jar>("kotlinSourcesJar") {
        from(sourceSets.main.get().allSource)
        destinationDirectory.set(file(Variables.jarsDir))
        archiveFileName.set(Variables.sourceJarFileName)
        archiveClassifier.set("sources")
    }
//    named<DokkaTask>("dokkaJavadoc"){
//        dokkaSourceSets{
//            named("main"){
//                documentedVisibilities.set(
//                    setOf(
//                        DokkaConfiguration.Visibility.PUBLIC,
//                        DokkaConfiguration.Visibility.PROTECTED
//                    )
//                )
//                sourceRoots.from(sourceSets.main.get().allSource)
//            }
//        }
//    }
//    named<Jar>("javadocJar"){
//        dependsOn(dokkaJavadoc)
//        from(dokkaJavadoc.get().outputs)
//        archiveClassifier.set("javadoc")
//        destinationDirectory.set(file(Variables.jarsDir))
//        archiveFileName.set(Variables.javadocJarFileName)
//    }

    register("create-metadata-files") {
        val version = Variables.modVersion.split(".")
        System.setProperty("line.separator", "\n") // Use LF instead of CRLF like a normal person

        File(projectDir, "mod_info.json")
            .writeText(
                """
                    # THIS FILE IS GENERATED BY build.gradle.kts. (Note that Starsector's json parser permits `#` for comments)
                    {
                        "id": "${Variables.modId}",
                        "name": "${Variables.modName}",
                        "author": "${Variables.author}",
                        "utility": "${Variables.isUtilityMod}",
                        "version": { "major":"${version[0]}", "minor": "${version[1]}", "patch": "${version[2]}" },
                        "description": "${Variables.description}",
                        "gameVersion": "${Variables.gameVersion}",
                        "jars":[${Variables.jars.joinToString() { "\"$it\"" }}],
                        "modPlugin":"${Variables.modPlugin}",
                        "dependencies": [
                            {
                                "id": "lw_lazylib",
                                "name": "LazyLib"
                            },
                            {
                                "id" : "MagicLib",
                                "name" : "MagicLib"
                            }
                        ]
                    }
                """.trimIndent()
            )

        File(projectDir, "data/config/version/version_files.csv")
            .writeText(
                """
                    version file
                    ${Variables.modId}.version

                """.trimIndent()
            )

        File(projectDir, "${Variables.modId}.version")
            .writeText(
                """
                    # THIS FILE IS GENERATED BY build.gradle.kts.
                    {
                        "masterVersionFile":"${Variables.masterVersionFile}",
                        "modName":"${Variables.modName}",
                        "modThreadId":${Variables.modThreadId},
                        "modVersion":
                        {
                            "major":${version[0]},
                            "minor":${version[1]},
                            "patch":${version[2]}
                        },
                        "directDownloadURL": "https://github.com/DesperatePeter/starsector-advanced-weapon-control/releases/download/${version[0]}.${version[1]}.${version[2]}/AdvancedGunneryControl-${version[0]}.${version[1]}.${version[2]}.zip",
                        "changelogURL": "https://raw.githubusercontent.com/DesperatePeter/starsector-advanced-weapon-control/master/changelog.txt"
                    }
                """.trimIndent()
            )


        File(projectDir, ".github/workflows/mod-folder-name.txt")
            .writeText(Variables.modFolderName)

        mkdir(Variables.jarsDir)

        doLast {
            File(Variables.jarsDir, "${Variables.jarFileNameBase}.pom")
                .writeText(
                    """
                    <project>
                        <modelVersion>4.0.0</modelVersion>

                        <groupId>agc</groupId>
                        <artifactId>AdvancedGunneryControl</artifactId>
                        <version>${Variables.modVersion}</version>
                    </project>
                """.trimIndent()
                )
        }

    }

    register("write-settings-file") {
        System.setProperty("line.separator", "\n")
        File(projectDir, "Settings.editme")
            .writeText(
                """
                   
                """.trimMargin()
            )
    }

    register("create-everything"){
        dependsOn(jar, kotlinSourcesJar, "write-settings-file", "create-metadata-files", "javadocJar")
    }

    // If enabled, will copy your mod to the /mods directory when run (and whenever gradle syncs).
    // Disabled by default, as it is not needed if your mod directory is symlinked into your /mods folder.
    register<Copy>("install-mod") {

        dependsOn(jar)
        dependsOn(kotlinSourcesJar)
        val enabled = false;

        if (!enabled) return@register

        println("Installing mod into Starsector mod folder...")

        val destinations = listOf(modInModsFolder)

        destinations.forEach { dest ->
            copy {
                from(projectDir)
                into(dest)
                exclude(".git", ".github", ".gradle", ".idea", ".run", "gradle")
            }
        }
    }
}

//tasks.test {
//    useJUnitPlatform()
//}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "17"
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17
